### ISSUE TITLE
poor stealing code

### ISSUE THREAD

**Issue by settlelol** [KSJaay/Alita#1]
i love you

**Comment by KSJaay** [comment]
This whole repository was meant to be for me to learn coding and I did use quite a lot of other repositories to learn the basics, that's mainly why I haven't updated this repository properly. That's also the reason why I haven't updated this repository in like 2-4 months and I am working on recreating this whole repository to make sure that it's not "stealing code" and it's all code that I've written. Thank you, hope that answers your question. If you have any problems let me know ❤️

**Comment by settlelol** [comment]
ah ok, sorry

**Comment by KSJaay** [comment]
It's all good, if you have any more problems just open up another issue. Will be closing this issue for now.
