### ISSUE TITLE
Implement slash commands 

### ISSUE THREAD

**Issue by ghost** [KSJaay/Alita#13]

**Comment by dword64** [comment]
Im working on a command handler for that dw

**Comment by KIIRONA** [comment]
You won't hurt to implement it in the export module of each command as an option :)

**Comment by KSJaay** [comment]
I won't be implementing/accepting any pull requests for slash commands until Discord.js fully supports it. Which will be when v13 is released

**Comment by dword64** [comment]
fair enough!

**Comment by KIIRONA** [comment]
Yes I completely agree with you :)
